---
title: "Publications"
site: distill::distill_website
css: pub.css
output:
  distill::distill_article
---

```{css, echo = F}
.fcolumns {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  width: 100%;
  margin: 0 10px
}
.fcolumn1 {
  flex: 10%;
}
.fcolumn2 {
  flex: 90%;
}

.fcolumn3 {
  flex: 15%;
}
.fcolumn4 {
  flex: 80%;
}

.fcolumnspace {
  flex: 5%;
}


d-title {
    display: none;
  }

.feat_img{
  height: auto;
  width: 95%!important;
}

d-article p {
margin-bottom: 0em;
}
```


```{r, include=FALSE}

suppressPackageStartupMessages({
  library(magrittr)
  library(dplyr)
  library(stringr)
})

source("R/cv_printing_functions_website.R")
source("R/publications.R")

# data/ is a committed snapshot of the CV google sheet; refresh with
# `Rscript R/refresh_data.R`. The build itself never hits the network.
CV <- create_CV_object(
  data_location = "data/",
  pdf_mode = 'false'
)
CV$entries_data$institution[CV$entries_data$institution=="N/A"] <- ""

```

<br>

```{r, echo = F, layout = "l-body-outset"}
htmltools::tags$h2("Publications")
```

```{r echo = FALSE, layout = "l-body-outset"}
render_publications(CV)
```

```{r, echo = F, layout = "l-body-outset"}
htmltools::tags$h3("Selected Presentations")
```

```{r results='asis', echo = FALSE, layout = "l-body-outset"}
CV %<>% print_section("presentations", glue_template = "poster")
```

```{r, echo = F, layout = "l-body-outset"}
htmltools::tags$h3("Other Publications")
```

```{r results='asis', echo = FALSE, layout = "l-body-outset"}
CV %<>% print_section("other publications", glue_template = "post")
```
